name: Dependabot auto-merge

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

concurrency:
  group: dependabot-auto-merge-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  dependabot:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-22.04
    steps:
      - name: Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Check if auto-merge applicable
        id: check
        env:
          UPDATE_TYPE: ${{ steps.meta.outputs.update-type }}
        run: |
          if [[ "$UPDATE_TYPE" == "version-update:semver-patch" ]] || \
             [[ "$UPDATE_TYPE" == "version-update:semver-minor" ]]; then
            echo "should_merge=true" >> $GITHUB_OUTPUT
          else
            echo "should_merge=false" >> $GITHUB_OUTPUT
          fi

      - name: Approve dependabot PR
        if: steps.check.outputs.should_merge == 'true'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.check.outputs.should_merge == 'true'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
