name: Notify release

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (leave empty for last one)"
jobs:
  set-env:
    runs-on: ubuntu-22.04
    outputs:
      tag: ${{ steps.set-env.outputs.tag }}
      repo_name: ${{ steps.set-env.outputs.repo_name }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Expose tag and repo_name
        id: set-env
        run: |
          if [ -n "$INPUT_TAG" ]; then
            TAG="$INPUT_TAG"
          else
            TAG=$(gh release view --json tagName -q '.tagName')
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

          REPO_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
        env:
          INPUT_TAG: ${{ github.event.inputs.tag }}
          GH_TOKEN: ${{ secrets.OPS_TOKEN }}

  notify-github-discussion:
    runs-on: ubuntu-22.04
    needs: set-env
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Extract changelog for tag
        run: |
          {
            echo 'CHANGELOG<<EOF'
            gh release view ${{ needs.set-env.outputs.tag }} --json body -q '.body'
            echo 'EOF'
          } >> "$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ secrets.OPS_TOKEN }}

      - name: Create an announcement discussion for release
        uses: abirismyname/create-discussion@v2.1.0
        with:
          title: üéâ ${{ needs.set-env.outputs.repo_name }} ${{ needs.set-env.outputs.tag }} released!
          body: |
            Hey frens! [${{ github.repository }}](https://github.com/${{ github.repository }}) `${{ needs.set-env.outputs.tag }}` just dropped! üöÄ

            Some fresh updates are here. Dive into the changelog and see what's cooking! üî•

            # Changelog

            ${{ env.CHANGELOG }}

            # Resources

            üìÑ Changelog: <https://github.com/${{ github.repository }}/releases/tag/${{ needs.set-env.outputs.tag }}>
            üõ†Ô∏è Official repo: <https://github.com/${{ github.repository }}>
            üí¨ Vibe with us on Discord: <${{ env.DISCORD_URL }}>
            üê¶ Catch us on Twitter: <${{ env.TWITTER_URL }}>
          repository-id: ${{ env.REPOSITORY_ID }}
          category-id: ${{ env.CATEGORY_ID }}
        env:
          GH_TOKEN: ${{ secrets.OPS_TOKEN }}
          DISCORD_URL: ${{ vars.DISCORD_URL }}
          TWITTER_URL: ${{ vars.TWITTER_URL }}
          REPOSITORY_ID: ${{ vars.DISCUSSIONS_REPOSITORY_ID }}
          CATEGORY_ID: ${{ vars.DISCUSSIONS_CATEGORY_ID }}

  update-docs:
    runs-on: ubuntu-22.04
    if: github.event_name != 'workflow_dispatch'
    steps:
      - name: Update modules docs repository
        uses: fjogeleit/http-request-action@v2
        with:
          url: "https://api.github.com/repos/axone-protocol/docs/actions/workflows/39152549/dispatches"
          method: "POST"
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.OPS_TOKEN }}"}'
          data: |-
            {
              "ref": "main",
              "inputs": {
                "version": "${{ github.event.release.tag_name }}",
                "repository": "${{github.repository}}",
                "section": "modules",
                "docs_directory": "docs/proto/*"
              }
            }

      - name: Update commands docs repository
        uses: fjogeleit/http-request-action@v2
        with:
          url: "https://api.github.com/repos/axone-protocol/docs/actions/workflows/39152549/dispatches"
          method: "POST"
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.OPS_TOKEN }}"}'
          data: |-
            {
              "ref": "main",
              "inputs": {
                "version": "${{ github.event.release.tag_name }}",
                "repository": "${{github.repository}}",
                "section": "commands",
                "docs_directory": "docs/command/*"
              }
            }

      - name: Update predicates docs repository
        uses: fjogeleit/http-request-action@v2
        with:
          url: "https://api.github.com/repos/axone-protocol/docs/actions/workflows/39152549/dispatches"
          method: "POST"
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.OPS_TOKEN }}"}'
          data: |-
            {
              "ref": "main",
              "inputs": {
                "version": "${{ github.event.release.tag_name }}",
                "repository": "${{github.repository}}",
                "section": "predicates",
                "docs_directory": "docs/predicate/*"
              }
            }

  update-docs-version:
    runs-on: ubuntu-22.04
    if: github.event_name != 'workflow_dispatch'
    steps:
      - name: Update docs version
        uses: fjogeleit/http-request-action@v2
        with:
          url: "https://api.github.com/repos/axone-protocol/docs/actions/workflows/98246586/dispatches"
          method: "POST"
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.OPS_TOKEN }}"}'
          data: |-
            {
              "ref": "main",
              "inputs": {
                "axonedVersion": "${{ github.event.release.tag_name }}"
              }
            }
