name: Notify release

on:
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-22.04
    steps:
      - name: Notify Discord
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: |-
            {
              "avatar_url": "https://avatars.githubusercontent.com/u/98603954?v=4",
              "username": "Bot Anik",
              "content": "ðŸš¨ A new version of @${{github.repository}} ${{ github.event.release.tag_name }} has been released! ðŸŽ‰\n\nðŸ‘‰ Changelog: https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}\nðŸ‘‰ Official repo: https://github.com/${{ github.repository }}"
            }

  update-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Update modules docs repository
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/okp4/docs/actions/workflows/39152549/dispatches'
          method: 'POST'
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.OPS_TOKEN }}"}'
          data: |-
            {
              "ref": "main",
              "inputs": {
                "version": "${{ github.event.release.tag_name }}",
                "repository": "${{github.repository}}",
                "section": "modules",
                "docs_directory": "docs/proto/*"
              }
            }

      - name: Update commands docs repository
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/okp4/docs/actions/workflows/39152549/dispatches'
          method: 'POST'
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.OPS_TOKEN }}"}'
          data: |-
            {
              "ref": "main",
              "inputs": {
                "version": "${{ github.event.release.tag_name }}",
                "repository": "${{github.repository}}",
                "section": "commands",
                "docs_directory": "docs/command/*"
              }
            }

      - name: Update predicates docs repository
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/okp4/docs/actions/workflows/39152549/dispatches'
          method: 'POST'
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.OPS_TOKEN }}"}'
          data: |-
            {
              "ref": "main",
              "inputs": {
                "version": "${{ github.event.release.tag_name }}",
                "repository": "${{github.repository}}",
                "section": "predicates",
                "docs_directory": "docs/predicates/*"
              }
            }

  update-docs-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Update docs version
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/okp4/docs/actions/workflows/37674835/dispatches'
          method: 'POST'
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.OPS_TOKEN }}"}'
          data: |-
            {
              "ref": "main",
              "inputs": {
                "axonedVersion": "${{ github.event.release.tag_name }}"
              }
            }
